language: haskell

ghc:
  - 7.8
  - 7.6
  - 7.4

before_install:
  - ghc-pkg list
  
install:
  - cabal install --dependencies-only --enable-tests
  - cabal configure -flib-Werror --enable-tests
  
script:
  - cabal build && cabal test
  